name: linting, testing, building 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 16.x ]
  
    steps:
    - uses: actions/checkout@v1
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install yarn
      run: npm install --global yarn
    - name: install modules
      run: yarn install
    - name: build production project
      run: yarn build:prod
    - name: linting typescript
      run: yarn lint:ts
      if: always()
    - name: linting css
      run: yarn lint:scss
      if: always()
    - name: unite testing
      run: yarn test:unite
      if: always()
    - name: start storybook
      run: yarn storybook:build
      if: always()
    - name: testing UI
      run: yarn test:ui:ci
      if: always()
